version: '3.8'

services:
  pandabot:
    container_name: panda-youtube
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./downloads:/app/downloads
    working_dir: /app/src
    command: python main.py
    environment:
      - API_TOKEN=${API_TOKEN}
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - pandabot
    volumes:
      - ./downloads:/usr/share/nginx/html/downloads
