version: '3.8'

services:
  pandadlbot:
    container_name: pandadlbot-youtube
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    working_dir: /app/src
    command: python main.py
    environment:
      - API_TOKEN=${API_TOKEN}
    ports:
      - "8000:8000"
    restart: always
