services:
  pandabot:
    container_name: panda-youtube
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
      - ./downloads:/app/downloads
      - ./database:/app/database
    working_dir: /app/src
    command: watchmedo auto-restart --pattern=*.py --recursive -- python -m main
    environment:
      - API_TOKEN=${API_TOKEN}
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    build: docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - pandabot
    environment:
      - DOMAIN_NAME=${DOMAIN}
    env_file:
      - .env
    volumes:
      - ./downloads:/usr/share/nginx/html/downloads